services:
  grafana:
    image: grafana/grafana
    restart: always
    expose:
      - 3000
    networks:
      - caddy-public
      - movie-tracker-metrics
      - grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    configs:
      - source: grafana_provisioning
        target: /etc/grafana/provisioning
    deploy:
      placement:
        constraints:
          - node.role != manager
          - node.labels.databases != true
  node-exporter:
    image: prom/node-exporter:latest
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - grafana
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - grafana
    deploy:
      placement:
        constraints:
          - node.role != manager
          - node.labels.databases != true
  loki:
    image: grafana/loki:3.6.7
    restart: unless-stopped
    networks:
      - grafana
    expose:
      - 3100
    command: -config.file=/etc/loki/local-config.yaml
    configs:
      - source: loki_config
        target: /etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  alloy:
    image: grafana/alloy:v1.14.0
    restart: unless-stopped
    networks:
      - grafana
      - movie-tracker-metrics
    configs:
      - source: alloy_config
        target: /etc/alloy/config.alloy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - alloy_data:/var/lib/alloy/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
#    command: --config.file=/etc/alloy/config.alloy --storage.path=/var/lib/alloy/data
    depends_on:
      - loki
    deploy:
      mode: global
      placement:
          constraints:
            - node.role == manager
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.2
    command: -logtostderr -docker_only
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    volumes:
      - type: bind
        source: /
        target: /rootfs
        read_only: true
      - type: bind
        source: /var/run
        target: /var/run
        read_only: true
      - type: bind
        source: /sys
        target: /sys
        read_only: true
      - type: bind
        source: /var/lib/docker
        target: /var/lib/docker
        read_only: true
      - type: bind
        source: /dev/disk
        target: /dev/disk
        read_only: true
    networks:
      - movie-tracker-metrics

configs:
  grafana_provisioning:
    file: ./provisioning
  prometheus_config:
    file: ./configs/prometheus.yml
  alloy_config:
    file: ./configs/config.alloy
  loki_config:
    file: ./configs/loki.yaml

volumes:
  grafana-storage:
  prometheus_data:
  loki_data:
  alloy_data:

networks:
  grafana:
    name: grafana
  movie-tracker-metrics:
    name: movie-tracker-metrics
    external: true
  caddy-public:
    name: caddy-public
    external: true
