export { default as AboutFaq } from "./ui/AboutFaq.vue"
export { default as AboutHero } from "./ui/AboutHero.vue"
export { default as AboutService } from "./ui/AboutService.vue"
export { default as BrandInformation } from "./ui/brand/BrandInformation.vue"
export { default as BrandLogos } from "./ui/brand/BrandLogos.vue"
export { default as AboutFeatures } from "./ui/features/AboutFeatures.vue"
export { default as AboutTeam } from "./ui/team/AboutTeam.vue"
