import React, { FC } from 'react';
import Head from 'next/head';

const Favorite: FC = () => {
  return (
    <div>
      <Head>
        <title>Movie Tracker | Избранное</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Favorite;
