import type { NextPage } from 'next';
import Head from 'next/head';
import HomePageContainer from '../components/containers/HomePageContainer';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Movie Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePageContainer />
    </>
  );
};

export default Home;
