receivers:
  otlp:
    protocols:
      grpc:
      http:
  redis:
    endpoint: ${env:REDIS_ENDPOINT}
    collection_interval: 10s
  postgresql:
    endpoint: ${env:POSTGRES_ENDPOINT}
    transport: tcp
    username: ${env:POSTGRES_USER}
    password: ${env:POSTGRES_PASSWORD}
    databases:
      - ${env:POSTGRES_DB}
    collection_interval: 10s
    tls:
      insecure: true

exporters:
  otlp:
    endpoint: ${env:UPTRACE_OTLP_ENDPOINT}
    tls:
      insecure: true
    headers:
      uptrace-dsn: ${env:UPTRACE_DSN}
      CF-Access-Client-Id: ${env:CF_ACCESS_CLIENT_ID}
      CF-Access-Client-Secret: ${env:CF_ACCESS_CLIENT_SECRET}

processors:
  resourcedetection:
    detectors: [env, system]
  cumulativetodelta:
  batch:
    timeout: 10s

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp, redis, postgresql]
      processors: [cumulativetodelta, batch, resourcedetection]
      exporters: [otlp]
