export { default as CloseIcon } from "~/assets/svg/icons/close.svg";
export { default as CheckMarkIcon } from "~/assets/svg/icons/check-mark.svg";
export { default as AddIcon } from "~/assets/svg/icons/add.svg";
export { default as ArrowIcon } from "~/assets/svg/icons/arrow.svg";
export { default as EditIcon } from "~/assets/svg/icons/edit.svg";
export { default as SearchIcon } from "~/assets/svg/icons/search.svg";
export { default as FavoriteIcon } from "~/assets/svg/icons/favorite.svg";
export { default as InFavoriteIcon } from "~/assets/svg/icons/in-favorite.svg";
export { default as UserIcon } from "~/assets/svg/icons/user.svg";
export { default as PlayIcon } from "~/assets/svg/icons/play.svg";
export { default as ListIcon } from "~/assets/svg/icons/list.svg";
export { default as ListCheckedIcon } from "~/assets/svg/icons/listChecked.svg";
export { default as ShareIcon } from "~/assets/svg/icons/share.svg";
export { default as SettingsIcon } from "~/assets/svg/icons/settings.svg";
export { default as TrashIcon } from "~/assets/svg/icons/trash.svg";
export { default as ChartCandleIcon } from "~/assets/svg/icons/chart-candle.svg";
export { default as EyeIcon } from "~/assets/svg/icons/eye.svg"
export { default as ArrowRightIcon } from "~/assets/svg/icons/arrowRight.svg"
export { default as ArrowRightBoldIcon } from "~/assets/svg/icons/arrowRightBold.svg"
export { default as CrossIcon } from "~/assets/svg/icons/cross.svg"
export { default as CheckIcon } from "~/assets/svg/icons/check.svg"
export { default as CardArrowTopIcon } from "assets/svg/icons/cardArrowTop.svg"
export { default as LogoIcon } from "assets/svg/icons/logo.svg"
export { default as PlanetIcon } from "assets/svg/icons/planet.svg"
export { default as LogoutIcon } from "assets/svg/icons/logout.svg"
export { default as BurgerMenuIcon } from "assets/svg/icons/burgerMenu.svg"
export { default as DiscordIcon } from "assets/svg/icons/discord.svg"
export { default as TelegramIcon } from "assets/svg/icons/telegram.svg"
export { default as GithubIcon } from "assets/svg/icons/github.svg"
export { default as TmdbLogoIcon } from "assets/svg/icons/tmdbLogo.svg"
export { default as VkontakteIcon } from "assets/svg/icons/vkontakte.svg"
export { default as YandexIcon } from "assets/svg/icons/yandex.svg"
export { default as GoogleIcon } from "assets/svg/icons/google.svg"
export { default as GithubProviderIcon } from "assets/svg/icons/githubProvider.svg"
export { default as StarIcon } from "assets/svg/icons/star.svg"
export { default as FacebookIcon } from "assets/svg/icons/facebook.svg"
export { default as InstagramIcon } from "assets/svg/icons/instagram.svg"
export { default as TiktokIcon } from "assets/svg/icons/tiktok.svg"
export { default as SelectArrowIcon } from "assets/svg/icons/selectArrow.svg"
export { default as ClocksIcon } from "assets/svg/icons/clocks.svg"
